export const propertyToDisplayName = {
	1: '1',
	10: '10',
	11: '11',
	12: '12',
	13: '13',
	14: '14',
	15: '15',
	16: '16',
	17: '17',
	18: '18',
	19: '19',
	2: '2',
	20: '20',
	21: '21',
	22: '22',
	23: '23',
	24: '24',
	25: '25',
	26: '26',
	27: '27',
	28: '28',
	29: '29',
	3: '3',
	30: '30',
	31: '31',
	32: '32',
	33: '33',
	34: '34',
	35: '35',
	36: '36',
	37: '37',
	38: '38',
	39: '39',
	4: '4',
	40: '40',
	41: '41',
	42: '42',
	43: '43',
	44: '44',
	45: '45',
	46: '46',
	5: '5',
	6: '6',
	7: '7',
	8: '8',
	9: '9',
	SoundHitDry: 'Sound Hit Dry',
	SoundHitDryVolume: 'Sound Hit Dry Volume',
	aa_gun: 'AA Gun',
	aa_minigun: 'AA Minigun',
	aa_missile: 'AA Missile',
	aa_missiles: 'AA Missiles',
	aakflak: 'AAK Flak',
	aamissile: 'AA Missile',
	aaweapon: 'AA Weapon',
	acceleration: 'Acceleration',
	accuracy: 'Accuracy',
	acidbomb: 'Acid Bomb',
	acidgoo: 'Acid Goo',
	acidspit: 'Acid Spit',
	activate: 'Activate',
	activatewhenbuilt: 'Activate When Built',
	adv_decklaser: 'Adv Deck Laser',
	adv_rocket: 'Adv Rocket',
	advdepthcharge: 'Adv Depth Charge',
	aimhull: 'Aim Hull',
	airfactory: 'Air Factory',
	airhoverfactor: 'Air Hover Factor',
	airsightdistance: 'Air Sight Distance',
	airstrafe: 'Air Strafe',
	allowNonBlockingAim: 'Allow Non Blocking Aim',
	alphaDecay: 'Alpha Decay',
	alphadecay: 'Alpha Decay',
	alwaysVisible: 'Always Visible',
	alwaysvisible: 'Always Visible',
	amd_rocket: 'AMD Rocket',
	amphibious: 'Amphibious',
	antiair: 'Anti Air',
	antiground: 'Anti Ground',
	area_mexT15_def: 'Area Mex T1.5 Defense',
	area_mex_def: 'Area Mex Defense',
	area_ondeath_ceg: 'Area On Death CEG',
	area_ondeath_damage: 'Area On Death Damage',
	area_ondeath_damageCeg: 'Area On Death Damage CEG',
	area_ondeath_range: 'Area On Death Range',
	area_ondeath_resistance: 'Area On Death Resistance',
	area_ondeath_time: 'Area On Death Time',
	areaofeffect: 'Area Of Effect', // Often abbreviated as AOE, but keeping full words for clarity unless specified
	arm_advsam: 'Arm Adv SAM',
	arm_artillery: 'Arm Artillery',
	arm_bats: 'Arm Bats',
	arm_bosscannon: 'Arm Boss Cannon',
	arm_bot_rocket: 'Arm Bot Rocket',
	arm_botrail: 'Arm Bot Rail',
	arm_bull: 'Arm Bull',
	arm_cir: 'Arm Cir',
	arm_fast: 'Arm Fast',
	arm_fatboy_notalaser: 'Arm Fatboy Notalaser',
	arm_ham: 'Arm Ham',
	arm_laser: 'Arm Laser',
	arm_laserh1: 'Arm Laser H1',
	arm_lightcannon: 'Arm Light Cannon',
	arm_lightlaser: 'Arm Light Laser',
	arm_pidr: 'Arm Pidr',
	arm_pidrbomb: 'Arm Pidr Bomb',
	arm_pincer_gauss: 'Arm Pincer Gauss',
	arm_seaadvbomb: 'Arm Sea Adv Bomb',
	arm_triton: 'Arm Triton',
	armaabot_missile1: 'Arm AA Bot Missile 1',
	armaabot_missile2: 'Arm AA Bot Missile 2',
	armadvbomb: 'Arm Adv Bomb',
	armageddon_blue_laser: 'Armageddon Blue Laser',
	armageddon_green_laser: 'Armageddon Green Laser',
	armagmheat: 'Arm AGM Heat',
	armah_weapon: 'Arm Ah Weapon',
	armair_torpedo: 'Arm Air Torpedo',
	armamb_gun: 'Arm Amb Gun',
	armamb_gun_high: 'Arm Amb Gun High',
	armamph_missile: 'Arm Amph Missile',
	armamph_weapon1: 'Arm Amph Weapon 1',
	armanac_weapon: 'Arm Anac Weapon',
	armatl_torpedo: 'Arm Atl Torpedo',
	armbantha_fire: 'Arm Bantha Fire',
	armbeamer_weapon: 'Arm Beamer Weapon',
	armbomb: 'Arm Bomb',
	armbot_missile: 'Arm Bot Missile',
	armcannon: 'Arm Cannon',
	armcl_missile: 'Arm Cl Missile',
	armcomlaser: 'Arm Com Laser',
	armcomlaserboss: 'Arm Com Laser Boss',
	armcomsealaser: 'Arm Com Sea Laser',
	armcomsealaserboss: 'Arm Com Sea Laser Boss',
	armdfly_paralyzer: 'Arm DFly Paralyzer',
	armemp_weapon: 'Arm EMP Weapon',
	armfhlt_laser: 'Arm Fhlt Laser',
	armflak_gun: 'Arm Flak Gun',
	armgremlin_gauss: 'Arm Gremlin Gauss',
	armlun_rocket: 'Arm Lun Rocket',
	armmav_weapon: 'Arm MAV Weapon',
	armmech_cannon: 'Arm Mech Cannon',
	armmg_weapon: 'Arm MG Weapon',
	armmh_weapon: 'Arm MH Weapon',
	armminivulc_weapon: 'Arm Minivulc Weapon',
	armor_class: 'Armor Class',
	armor_type: 'Armor Type',
	armpb_weapon: 'Arm PB Weapon',
	armrl_missile: 'Arm RL Missile',
	armscab_weapon: 'Arm Scab Weapon',
	armseap_weapon1: 'Arm Seap Weapon 1',
	armserp_weapon: 'Arm Serp Weapon',
	armsfig_weapon: 'Arm SFig Weapon',
	armsh_weapon: 'Arm SH Weapon',
	armshlt_dead: 'Arm Shlt Dead',
	armshlt_heap: 'Arm Shlt Heap',
	armsmart_torpedo: 'Arm Smart Torpedo',
	armsnipe_weapon: 'Arm Snipe Weapon',
	armtruck_aa: 'Arm Truck AA',
	armtruck_missile: 'Arm Truck Missile',
	armtruck_rocket: 'Arm Truck Rocket',
	armvtol_advmissile: 'Arm VTOL Adv Missile',
	armvtol_missile: 'Arm VTOL Missile',
	armwar_laser: 'Arm War Laser',
	ata: 'ATA', // Assuming acronym
	atadr: 'ATADR', // Assuming acronym
	atam: 'ATAM', // Assuming acronym
	atdronewep: 'AT Drone Wep',
	attackrunlength: 'Attack Run Length',
	autoheal: 'Auto Heal',
	avoidfeature: 'Avoid Feature',
	avoidfriendly: 'Avoid Friendly',
	avoidground: 'Avoid Ground',
	avoidneutral: 'Avoid Neutral',
	backlauncher: 'Back Launcher',
	badTargetCategory: 'Bad Target Category',
	badtargetcategory: 'Bad Target Category',
	banisher: 'Banisher',
	bankingallowed: 'Banking Allowed',
	bankscale: 'Bank Scale',
	bantha_rocket: 'Bantha Rocket',
	banthfootstep: 'Bantha Footstep',
	basename: 'Base Name',
	beamTTL: 'Beam TTL',
	beamburst: 'Beam Burst',
	beamdecay: 'Beam Decay',
	beamtime: 'Beam Time',
	beamttl: 'Beam TTL',
	bfido: 'B Fido', // Assuming B is separate
	bigfootstep: 'Big Footstep',
	birdshot: 'Birdshot',
	bladewing_lyzer: 'Bladewing Lyzer',
	blocking: 'Blocking',
	bloodyeggs: 'Bloody Eggs',
	bogus_missile: 'Bogus Missile',
	bombardier_weapon: 'Bombardier Weapon',
	botcannon: 'Bot Cannon',
	bounce: 'Bounce',
	bounceSlip: 'Bounce Slip',
	bounceexplosiongenerator: 'Bounce Explosion Generator',
	bouncerebound: 'Bounce Rebound',
	bounceslip: 'Bounce Slip',
	brakerate: 'Brake Rate',
	build: 'Build',
	buildangle: 'Build Angle',
	buildcostenergy: 'Energy Cost',
	buildcostmetal: 'Metal Cost',
	builddistance: 'Build Distance',
	builder: 'Builder',
	buildinggrounddecalalpha: 'Building Ground Decal Alpha',
	buildinggrounddecaldecayspeed: 'Building Ground Decal Decay Speed',
	buildinggrounddecalsizex: 'Building Ground Decal Size X',
	buildinggrounddecalsizey: 'Building Ground Decal Size Y',
	buildinggrounddecaltype: 'Building Ground Decal Type',
	buildingmask: 'Building Mask',
	buildoptions: 'Build Options',
	buildpic: 'Build Picture',
	buildtime: 'Build Time',
	burnblow: 'Burn Blow',
	burst: 'Burst',
	burstControlWhenOutOfArc: 'Burst Control When Out Of Arc',
	burst_aa_missile: 'Burst AA Missile',
	burst_length: 'Burst Length',
	burstcontrolwhenoutofarc: 'Burst Control When Out Of Arc',
	burstrate: 'Burst Rate',
	cameraShake: 'Camera Shake',
	camerashake: 'Camera Shake',
	canSelfDestruct: 'Can Self Destruct',
	canareaattack: 'Can Area Attack',
	canassist: 'Can Assist',
	canattack: 'Can Attack',
	canattackground: 'Can Attack Ground',
	canbuild: 'Can Build',
	cancapture: 'Can Capture',
	canceldestruct: 'Cancel Destruct',
	cancloak: 'Can Cloak',
	cancrash: 'Can Crash',
	candgun: 'Can D-Gun',
	canfight: 'Can Fight',
	canfly: 'Can Fly',
	canguard: 'Can Guard',
	canhover: 'Can Hover',
	canland: 'Can Land',
	canloopbackattack: 'Can Loopback Attack',
	canmanualfire: 'Can Manual Fire',
	canmove: 'Can Move',
	cannon: 'Cannon',
	cannon1name: 'Cannon 1 Name',
	cannonuw: 'Cannon UW', // Underwater?
	canpatrol: 'Can Patrol',
	canreclaim: 'Can Reclaim',
	canrepair: 'Can Repair',
	canrepeat: 'Can Repeat',
	canrestore: 'Can Restore',
	canresurrect: 'Can Resurrect',
	canselfdestruct: 'Can Self Destruct',
	canselfrepair: 'Can Self Repair',
	canstop: 'Can Stop',
	cansubmerge: 'Can Submerge',
	cant: 'Cant',
	cantbetransported: 'Cant Be Transported',
	capturable: 'Capturable',
	capture: 'Capture',
	capturespeed: 'Capture Speed',
	castshadow: 'Cast Shadow',
	category: 'Category',
	cdragonseyes_dead: 'CDragonseyes Dead', // Keep C prefix?
	cegtag: 'CEG Tag',
	chaseweapon: 'Chase Weapon',
	childreninheritxp: 'Children Inherit XP',
	cloak: 'Cloak',
	cloakable: 'Cloakable',
	cloakcost: 'Cloak Cost',
	cloakcostmoving: 'Cloak Cost Moving',
	close_plasma: 'Close Plasma',
	cluster_munition: 'Cluster Munition',
	clusternapalm: 'Cluster Napalm',
	clusterplasma: 'Cluster Plasma',
	coax_depthcharge: 'Coax Depth Charge',
	cobkickbackrestorespeed: 'Cob Kickback Restore Speed',
	collide: 'Collide',
	collideFriendly: 'Collide Friendly',
	collide_friendly: 'Collide Friendly',
	collideenemy: 'Collide Enemy',
	collidefeature: 'Collide Feature',
	collidefirebase: 'Collide Firebase',
	collidefriendly: 'Collide Friendly',
	collideground: 'Collide Ground',
	collideneutral: 'Collide Neutral',
	collision: 'Collision',
	collisionSize: 'Collision Size',
	collisionsize: 'Collision Size',
	collisionspherescale: 'Collision Sphere Scale',
	collisionvolumeoffsets: 'Collision Volume Offsets',
	collisionvolumescales: 'Collision Volume Scales',
	collisionvolumetest: 'Collision Volume Test',
	collisionvolumetype: 'Collision Volume Type',
	colormap: 'Color Map',
	combatradius: 'Combat Radius',
	commandfire: 'Command Fire',
	commando_back_cannon: 'Commando Back Cannon',
	commando_blaster: 'Commando Blaster',
	commando_stunner: 'Commando Stunner',
	comment: 'Comment',
	controlblob: 'Control Blob',
	cor_advsam: 'Cor Adv SAM',
	cor_artillery: 'Cor Artillery',
	cor_bats: 'Cor Bats',
	cor_batslaser: 'Cor Bats Laser',
	cor_bot_rocket: 'Cor Bot Rocket',
	cor_burst_laser: 'Cor Burst Laser',
	cor_canlaser: 'Cor Can Laser',
	cor_croc: 'Cor Croc',
	cor_crus: 'Cor Crus',
	cor_erad: 'Cor Erad',
	cor_gol: 'Cor Gol',
	cor_heat_laser: 'Cor Heat Laser',
	cor_intimidator: 'Cor Intimidator',
	cor_laser: 'Cor Laser',
	cor_laserh1: 'Cor Laser H1',
	cor_lightlaser: 'Cor Light Laser',
	cor_mort: 'Cor Mort',
	cor_parrow: 'Cor Parrow',
	cor_reap: 'Cor Reap',
	cor_seaadvbomb: 'Cor Sea Adv Bomb',
	cor_termite_laser: 'Cor Termite Laser',
	cor_tiger_laser: 'Cor Tiger Laser',
	coraabot_missile1: 'Cor AA Bot Missile 1',
	coraabot_missile2: 'Cor AA Bot Missile 2',
	coraabot_missile3: 'Cor AA Bot Missile 3',
	coraabot_missile4: 'Cor AA Bot Missile 4',
	coradvbomb: 'Cor Adv Bomb',
	corah_weapon: 'Cor Ah Weapon',
	coramph_weapon1: 'Cor Amph Weapon 1',
	coramph_weapon2: 'Cor Amph Weapon 2',
	coratl_torpedo: 'Cor Atl Torpedo',
	corbhmth_weapon: 'Cor Bhmth Weapon',
	corbomb: 'Cor Bomb',
	corbot_missile: 'Cor Bot Missile',
	corcomeyelaser: 'Cor Com Eye Laser',
	corcomlaser: 'Cor Com Laser',
	corcomlaserboss: 'Cor Com Laser Boss',
	corcomsealaser: 'Cor Com Sea Laser',
	corcomsealaserboss: 'Cor Com Sea Laser Boss',
	corethickness: 'Core Thickness',
	corfhlt_laser: 'Cor Fhlt Laser',
	corgol_sidelaser: 'Cor Gol Side Laser',
	corhrk_rocket: 'Cor HRK Rocket',
	corkorg_fire: 'Cor Korg Fire',
	corkorg_laser: 'Cor Korg Laser',
	corkorg_rocket: 'Cor Korg Rocket',
	corlevlr_weapon: 'Cor Levlr Weapon',
	cormabm_weapon: 'Cor MABM Weapon',
	cormexp_rocket: 'Cor MExp Rocket',
	cormh_weapon: 'Cor MH Weapon',
	corminibuzz_weapon: 'Cor Minibuzz Weapon',
	corpse: 'Wreckage Type',
	corrl_missile: 'Cor RL Missile',
	corsfig_weapon: 'Cor SFig Weapon',
	corsok_laser: 'Cor Sok Laser',
	corsumo_weapon: 'Cor Sumo Weapon',
	cortoast_gun: 'Cor Toast Gun',
	cortoast_gun_high: 'Cor Toast Gun High',
	cortron_weapon: 'Cor Tron Weapon',
	cortruck_aa: 'Cor Truck AA',
	cortruck_missile: 'Cor Truck Missile',
	cortruck_rocket: 'Cor Truck Rocket',
	corvtol_advmissile: 'Cor VTOL Adv Missile',
	corvtol_missile: 'Cor VTOL Missile',
	corwar_laser: 'Cor War Laser',
	corwolv_gun: 'Cor Wolv Gun',
	cotd_depthcharge: 'COTD Depth Charge', // Assuming COTD is acronym
	count: 'Count',
	coverage: 'Coverage',
	crashable: 'Crashable',
	crashexplosiongenerators: 'Crash Explosion Generators',
	craterareaofeffect: 'Crater Area Of Effect',
	craterboost: 'Crater Boost',
	cratermult: 'Crater Multiplier',
	crawl_detonator: 'Crawl Detonator',
	crawl_dummy: 'Crawl Dummy',
	crblmssl: 'CRBL MSSL', // Assuming acronyms
	cruisealt: 'Cruise Altitude',
	cruisealtitude: 'Cruise Altitude',
	crushresistance: 'Crush Resistance',
	customparams: 'Custom Parameters',
	customrange: 'Custom Range',
	cvbuildable: 'CV Buildable', // Carrier Vessel?
	cylindertargeting: 'Cylinder Targeting',
	damage: 'Damage',
	damage_per_cost: 'Damage Per Cost',
	damage_type: 'Damage Type',
	damageareaofeffect: 'Damage Area Of Effect',
	damagemodifier: 'Damage Modifier',
	dance: 'Dance',
	dclaw: 'D Claw', // Assuming D is separate
	deactivate: 'Deactivate',
	dead: 'Dead',
	decoration: 'Decoration',
	decoyfor: 'Decoy For',
	def: 'Definition', // Or Defense? Assuming Definition based on context like weapondefs
	defaultmissiontype: 'Default Mission Type',
	depthcharge: 'Depth Charge',
	description: 'Description',
	detonaterange: 'Detonate Range',
	disable_when_no_air: 'Disable When No Air',
	disintegrator: 'Disintegrator',
	disintegratorxl: 'Disintegrator XL',
	distance_stun_multiplier: 'Distance Stun Multiplier',
	dmaw: 'DMAW', // Assuming acronym
	doomsday_green_laser: 'Doomsday Green Laser',
	doomsday_red_laser: 'Doomsday Red Laser',
	dps: 'DPS',
	dragon_missileh: 'Dragon Missile H',
	dragonmawh: 'Dragon Maw H',
	dragonseyes_dead: 'Dragonseyes Dead',
	dreadovercharge: 'Dread Overcharge',
	dreadshot: 'Dread Shot',
	driftratio: 'Drift Ratio',
	drone: 'Drone',
	duration: 'Duration',
	edgeeffectiveness: 'Edge Effectiveness',
	edragon_missile: 'E Dragon Missile', // Assuming E is separate
	effigy: 'Effigy',
	effigy_offset: 'Effigy Offset',
	emg: 'EMG',
	emgx: 'EMG X',
	emp: 'EMP',
	empflashbang: 'EMP Flashbang',
	empgrenade: 'EMP Grenade',
	empmissile: 'EMP Missile',
	energyconv_capacity: 'Energy Converter Capacity',
	energyconv_efficiency: 'Energy Converter Efficiency',
	energycost: 'Energy Cost Per Shot', // Distinguish from buildcostenergy
	energymake: 'Energy Make',
	energymultiplier: 'Energy Multiplier',
	energypershot: 'Energy Per Shot',
	energystorage: 'Energy Storage',
	energyupkeep: 'Energy Upkeep',
	evocomlvl: 'Evo Com Level', // Guessing
	evolution_condition: 'Evolution Condition',
	evolution_health_transfer: 'Evolution Health Transfer',
	evolution_power_multiplier: 'Evolution Power Multiplier',
	evolution_power_threshold: 'Evolution Power Threshold',
	evolution_target: 'Evolution Target',
	evolution_timer: 'Evolution Timer',
	exata: 'EX ATA', // Assuming EX prefix
	exemptcategory: 'Exempt Category',
	exp_heavyrocket: 'Exp Heavy Rocket',
	explodeas: 'Explode As',
	explosiongenerator: 'Explosion Generator',
	explosiongenerators: 'Explosion Generators',
	explosionscar: 'Explosion Scar',
	extractsmetal: 'Extracts Metal',
	eyelaser: 'Eye Laser',
	fallOffRate: 'Fall Off Rate',
	fall_damage_multiplier: 'Fall Damage Multiplier',
	falloffrate: 'Fall Off Rate',
	far_plasma: 'Far Plasma',
	fastAutoRetargeting: 'Fast Auto Retargeting',
	fastautoretargeting: 'Fast Auto Retargeting',
	featuredefs: 'Feature Definitions',
	ferret_missile: 'Ferret Missile',
	festorbeam: 'Festor Beam',
	fighter: 'Fighter',
	fireTolerance: 'Fire Tolerance',
	fire_rate: 'Fire Rate',
	firestarter: 'Fire Starter',
	firestate: 'Fire State',
	firesubmersed: 'Fire Submersed',
	firetolerance: 'Fire Tolerance',
	firingceg: 'Firing CEG',
	fixedlauncher: 'Fixed Launcher',
	flak: 'Flak',
	flameGFXTime: 'Flame GFX Time',
	flame_thrower: 'Flame Thrower',
	flamegfxtime: 'Flame GFX Time',
	flamer: 'Flamer',
	flamethrower: 'Flamethrower',
	flamethrower_ce: 'Flamethrower CE', // Combat Effective? Custom Effect?
	flamethrowermain: 'Flamethrower Main',
	flamethrowerspike: 'Flamethrower Spike',
	flare1name: 'Flare 1 Name',
	flashlightmin: 'Flashlight Min',
	flea_laser: 'Flea Laser',
	flightTime: 'Flight Time',
	flighttime: 'Flight Time',
	floater: 'Floater',
	fmd_rocket: 'FMD Rocket',
	footprintx: 'Footprint X',
	footprintz: 'Footprint Z',
	frontgun: 'Front Gun',
	ga2: 'GA 2', // Assuming GA prefix
	gator_laser: 'Gator Laser',
	gator_laserx: 'Gator Laser X',
	gauss: 'Gauss',
	geothermal: 'Geothermal',
	goo: 'Goo',
	goolauncher: 'Goo Launcher',
	gravityaffected: 'Gravity Affected',
	groundbounce: 'Ground Bounce',
	gun: 'Gun',
	hardstop: 'Hard Stop',
	health: 'Health',
	heap: 'Heap',
	heat_ray: 'Heat Ray',
	heatray1: 'Heat Ray 1',
	heatraylarge: 'Heat Ray Large',
	heatroy: 'Heat Ray', // Typo fixed based on context
	heavy_torpedo: 'Heavy Torpedo',
	heavylaser: 'Heavy Laser',
	heavyplasma: 'Heavy Plasma',
	heightboostfactor: 'Height Boost Factor',
	hidedamage: 'Hide Damage',
	highTrajectory: 'High Trajectory',
	hightrajectory: 'High Trajectory',
	hllt_1: 'HLLT 1',
	hllt_2: 'HLLT 2',
	hllt_3: 'HLLT 3',
	hllt_4: 'HLLT 4',
	hllt_bottom: 'HLLT Bottom',
	hllt_top: 'HLLT Top',
	holdsteady: 'Hold Steady',
	hoverAttack: 'Hover Attack',
	hoverattack: 'Hover Attack',
	hplasma: 'H Plasma', // Heavy Plasma? High Plasma?
	i18nfromunit: 'Inherit Locale From Unit',
	icontype: 'Icon Type',
	idleautoheal: 'Idle Auto Heal',
	idletime: 'Idle Time',
	impactonly: 'Impact Only',
	impulse_factor: 'Impulse Factor',
	impulseboost: 'Impulse Boost',
	impulsefactor: 'Impulse Factor',
	inheritxpratemultiplier: 'Inherit XP Rate Multiplier',
	initcloak: 'Init Cloak',
	initcloaked: 'Init Cloaked',
	instantselfd: 'Instant Self Destruct',
	intensity: 'Intensity',
	interceptedByShieldType: 'Intercepted By Shield Type',
	interceptedbyshieldtype: 'Intercepted By Shield Type',
	interceptor: 'Interceptor',
	isairbase: 'Is Air Base',
	iscommander: 'Is Commander',
	isdecoycommander: 'Is Decoy Commander',
	istargetingupgrade: 'Is Targeting Upgrade',
	janus_rocket: 'Janus Rocket',
	juggernaut_bottom: 'Juggernaut Bottom',
	juggernaut_fire: 'Juggernaut Fire',
	juggernaut_top: 'Juggernaut Top',
	juno_pulse: 'Juno Pulse',
	juno_pulse_ghost: 'Juno Pulse Ghost',
	juno_pulse_mini: 'Juno Pulse Mini',
	kamikaze: 'Kamikaze',
	kamikazedistance: 'Kamikaze Distance',
	karg_shoulder: 'Karg Shoulder',
	kickback: 'Kickback',
	kmaw: 'KMAW', // Assuming acronym
	krogfootstep: 'Krog Footstep',
	krogkick: 'Krog Kick',
	krogweaponaim: 'Krog Weapon Aim',
	krogweaponrestore: 'Krog Weapon Restore',
	krowbosslaser: 'Krow Boss Laser',
	krowbosslaser2: 'Krow Boss Laser 2',
	krowlaser: 'Krow Laser',
	krowlaser2: 'Krow Laser 2',
	krowlaserh: 'Krow Laser H',
	largebeamlaser: 'Large Beam Laser',
	laser: 'Laser',
	laserFlareSize: 'Laser Flare Size',
	laserflaresize: 'Laser Flare Size',
	leadbonus: 'Lead Bonus',
	leadlimit: 'Lead Limit',
	leavetracks: 'Leave Tracks',
	leg_amph_gauss: 'Leg Amph Gauss',
	legacyname: 'Legacy Name',
	legah_gun: 'Leg Ah Gun',
	legair_torp: 'Leg Air Torp',
	legcomlaser: 'Leg Com Laser',
	legflak_gun: 'Leg Flak Gun',
	legfloat_gatling: 'Leg Float Gatling',
	legfloat_gauss: 'Leg Float Gauss',
	leggun: 'Leg Gun',
	legheatray: 'Leg Heat Ray',
	legicbm: 'Leg ICBM',
	legion_shotgun: 'Legion Shotgun',
	legkeres_cannon: 'Leg Keres Cannon',
	legkeres_gatling: 'Leg Keres Gatling',
	legmed_missile: 'Leg Med Missile',
	legmgplasma: 'Leg MG Plasma',
	legmh_weapon: 'Leg MH Weapon',
	legner_weapon: 'Leg Ner Weapon',
	legphsound: 'Leg Ph Sound',
	legphtarg: 'Leg Ph Target',
	legrl_missile: 'Leg RL Missile',
	levelground: 'Level Ground',
	lightning: 'Lightning',
	loadingradius: 'Loading Radius',
	longgun: 'Long Gun',
	losemitheight: 'Los Emit Height', // Line Of Sight
	lrpc: 'LRPC',
	lumamult: 'Luma Multiplier',
	machinegun: 'Machine Gun',
	madsam_missile: 'Mad SAM Missile',
	maindir: 'Main Direction',
	maneuverleashlength: 'Maneuver Leash Length',
	martyrbomb: 'Martyr Bomb',
	mass: 'Mass',
	maxacc: 'Max Acceleration',
	maxaileron: 'Max Aileron',
	maxangledif: 'Max Angle Difference',
	maxbank: 'Max Bank',
	maxdamage: 'Max Health', // Common override
	maxdec: 'Max Deceleration',
	maxelevator: 'Max Elevator',
	maxpitch: 'Max Pitch',
	maxrange: 'Max Range',
	maxreversevelocity: 'Max Reverse Velocity',
	maxrudder: 'Max Rudder',
	maxslope: 'Max Slope',
	maxvelocity: 'Max Speed', // Common override
	maxwaterdepth: 'Max Water Depth',
	mech_rapidlaser: 'Mech Rapid Laser',
	med_emg: 'Med EMG',
	mediumplasma: 'Medium Plasma',
	melee: 'Melee',
	meleeBig: 'Melee Big',
	metal_extractor: 'Metal Extractor',
	metalcost: 'Metal Cost Per Shot', // Distinguish from buildcostmetal
	metalmake: 'Metal Make',
	metalpershot: 'Metal Per Shot',
	metalstorage: 'Metal Storage',
	mg_guns: 'MG Guns',
	minIntensity: 'Min Intensity',
	mincloakdistance: 'Min Cloak Distance',
	mine: 'Mine',
	minerange: 'Mine Range',
	minesweep: 'Mine Sweep',
	minesweeper: 'Mine Sweeper',
	minimum_respawn_stun: 'Minimum Respawn Stun',
	minintensity: 'Min Intensity',
	ministarfire: 'Mini Starfire',
	minwaterdepth: 'Min Water Depth',
	missile: 'Missile',
	mobileflak: 'Mobile Flak',
	mobilestandorders: 'Mobile Stand Orders',
	model: 'Model',
	model_author: 'Model Author',
	mortar: 'Mortar',
	movementclass: 'Movement Class',
	moverate1: 'Move Rate 1',
	movestate: 'Move State',
	movingaccuracy: 'Moving Accuracy',
	mygravity: 'My Gravity',
	name: 'Display Name', // Human-readable name
	nanocolor: 'Nano Color',
	napalmbombs: 'Napalm Bombs',
	napalmmissile: 'Napalm Missile',
	neutral_when_closed: 'Neutral When Closed',
	newdmaw: 'New DMAW',
	noautofire: 'No Auto Fire',
	nochase: 'No Chase',
	nochasecategory: 'No Chase Category',
	noexplode: 'No Explode',
	nogap: 'No Gap',
	nohealthbars: 'No Health Bars',
	nopvebuilder: 'No PvE Builder',
	norestrict: 'No Restrict',
	normalmaps: 'Normal Maps',
	normaltex: 'Normal Texture',
	noselfdamage: 'No Self Damage',
	nuclear_launch: 'Nuclear Launch',
	nuclear_missile: 'Nuclear Missile',
	nuketest: 'Nuke Test',
	nuketestcor: 'Nuke Test Cor',
	numbounce: 'Num Bounce',
	objectify: 'Objectify',
	objectname: 'Internal Name', // Internal engine/script name
	off_on_stun: 'Off On Stun',
	ok: 'OK',
	old_armsnipe_weapon: 'Old Arm Snipe Weapon',
	onlytargetcategory: 'Only Target Category',
	onlytargetcategory2: 'Only Target Category 2',
	onoffable: 'On Offable',
	onoffname: 'On Off Name',
	ownerExpAccWeight: 'Owner XP Acc Weight',
	ownerexpaccweight: 'Owner XP Acc Weight',
	paralyze: 'Paralyze',
	paralyzemultiplier: 'Paralyze Multiplier',
	'paralyze-dps': 'Paralyze DPS',
	paralyzer: 'Paralyzer',
	paralyzetime: 'Paralyze Time',
	paratrooper: 'Paratrooper',
	parentsinheritxp: 'Parents Inherit XP',
	pieceexplosiongenerators: 'Piece Explosion Generators',
	plasma: 'Plasma',
	plasma_high: 'Plasma High',
	predictBoost: 'Predict Boost',
	predictboost: 'Predict Boost',
	projectiles: 'Projectiles',
	proximityPriority: 'Proximity Priority',
	proximitypriority: 'Proximity Priority',
	pulsespeed: 'Pulse Speed',
	pushresistant: 'Push Resistant',
	quickshot_cannon: 'Quickshot Cannon',
	radardistance: 'Radar Distance',
	radardistancejam: 'Radar Distance Jam',
	radaremitheight: 'Radar Emit Height',
	railgun: 'Railgun',
	railgunt2: 'Railgun T2',
	railgunt3: 'Railgun T3',
	range: 'Range',
	range_max: 'Range Max',
	range_min: 'Range Min',
	rangefinder: 'Range Finder',
	rangexpscale: 'Range XP Scale',
	rapidnapalm: 'Rapid Napalm',
	raptorparalyzerbig: 'Raptor Paralyzer Big',
	raptorparalyzersmall: 'Raptor Paralyzer Small',
	reclaimable: 'Reclaimable',
	reclaimspeed: 'Reclaim Speed',
	releaseheld: 'Release Held',
	reload_time: 'Reload Time',
	reloadtime: 'Reload Time',
	removestop: 'Remove Stop',
	removewait: 'Remove Wait',
	repair: 'Repair',
	repairable: 'Repairable',
	repulsor: 'Repulsor',
	repulsor1: 'Repulsor 1',
	respawn_announcement: 'Respawn Announcement',
	restoretime: 'Restore Time',
	rflrpc: 'RF LRPC', // Assuming RF prefix
	rgbcolor: 'RGB Color',
	rgbcolor2: 'RGB Color 2',
	rocket: 'Rocket',
	rocket_split: 'Rocket Split',
	rockrestorespeed: 'Rock Restore Speed',
	rockspeed: 'Rock Speed',
	rockstrength: 'Rock Strength',
	rockteeth: 'Rock Teeth',
	rockteethx: 'Rock Teeth X',
	salvo_size: 'Salvo Size',
	script: 'Script',
	scrollspeed: 'Scroll Speed',
	sdmssl: 'SD MSSL', // Assuming acronyms
	sea_repulsor: 'Sea Repulsor',
	seismicdistance: 'Seismic Distance',
	seismicsignature: 'Seismic Signature',
	select: 'Select',
	selfdestructas: 'Self Destruct As',
	selfdestructcountdown: 'Self Destruct Countdown',
	semiauto: 'Semi Auto',
	sentinel_depthcharge: 'Sentinel Depth Charge',
	separation: 'Separation',
	separationDistance: 'Separation Distance',
	sfxtypes: 'SFX Types', // Special Effects
	shield: 'Shield',
	shield_color_mult: 'Shield Color Multiplier',
	shield_power: 'Shield Power',
	shield_radius: 'Shield Radius',
	shield_rate: 'Shield Rate',
	shield_recharge: 'Shield Recharge',
	shiva_gun: 'Shiva Gun',
	shiva_rocket: 'Shiva Rocket',
	shocker: 'Shocker',
	shocker_high: 'Shocker High',
	shocker_low: 'Shocker Low',
	shortgun: 'Short Gun',
	shot: 'Shot',
	shotgun: 'Shotgun',
	showplayername: 'Show Player Name',
	side: 'Side', // Faction
	sightdistance: 'Sight Distance',
	sightemitheight: 'Sight Emit Height',
	size: 'Size',
	sizeDecay: 'Size Decay',
	sizedecay: 'Size Decay',
	sizegrowth: 'Size Growth',
	skybeam: 'Sky Beam',
	slaveTo: 'Slave To',
	slaveto: 'Slave To',
	sleevename: 'Sleeve Name',
	small_weapon: 'Small Weapon',
	smart_trajectory_dummy: 'Smart Trajectory Dummy',
	smokePeriod: 'Smoke Period',
	smokeTrailCastShadow: 'Smoke Trail Cast Shadow',
	smokecolor: 'Smoke Color',
	smokeperiod: 'Smoke Period',
	smokesize: 'Smoke Size',
	smoketime: 'Smoke Time',
	smoketrail: 'Smoke Trail',
	smoketrailcastshadow: 'Smoke Trail Cast Shadow',
	smoothanim: 'Smooth Animation',
	solar: 'Solar',
	sonardistance: 'Sonar Distance',
	sonarstealth: 'Sonar Stealth',
	soundhit: 'Sound Hit',
	soundhitdry: 'Sound Hit Dry',
	soundhitdryvolume: 'Sound Hit Dry Volume',
	soundhitvolume: 'Sound Hit Volume',
	soundhitwet: 'Sound Hit Wet',
	soundhitwetvolume: 'Sound Hit Wet Volume',
	sounds: 'Sounds',
	soundstart: 'Sound Start',
	soundstartvolume: 'Sound Start Volume',
	soundtrigger: 'Sound Trigger',
	spawnmeteor: 'Spawn Meteor',
	speed: 'Speed',
	speedtofront: 'Speed To Front',
	spider: 'Spider',
	spike_acid_blob: 'Spike Acid Blob',
	spike_emp_blob: 'Spike EMP Blob',
	sprayAngle: 'Spray Angle',
	sprayangle: 'Spray Angle',
	stages: 'Stages',
	standingmoveorder: 'Standing Move Order',
	starfire: 'Starfire',
	startvelocity: 'Start Velocity',
	stealth: 'Stealth',
	stiletto_bomb: 'Stiletto Bomb',
	stoa_missile: 'STOA Missile', // Assuming STOA acronym
	stockpile: 'Stockpile',
	stockpiletime: 'Stockpile Time',
	strafetoattack: 'Strafe To Attack',
	subfolder: 'Subfolder',
	super_missile: 'Super Missile',
	t2heatray: 'T2 Heat Ray',
	t3_rail_accelerator: 'T3 Rail Accelerator',
	targetBorder: 'Target Border',
	targetable: 'Targetable',
	targetborder: 'Target Border',
	targetmoveerror: 'Target Move Error',
	tawf113_weapon: 'TAWF 113 Weapon', // Assuming TAWF acronym
	td_depthcharge: 'TD Depth Charge',
	techlevel: 'Tech Level',
	tehlazerofdewm: 'Teh Lazer Of Dewm',
	terraformspeed: 'Terraform Speed',
	texture1: 'Texture 1',
	texture2: 'Texture 2',
	texture3: 'Texture 3',
	thermite_laser: 'Thermite Laser',
	thickness: 'Thickness',
	thunder: 'Thunder',
	tidalgenerator: 'Tidal Generator',
	tilelength: 'Tile Length',
	tmaw: 'TMAW', // Assuming acronym
	tolerance: 'Tolerance',
	topgunaa: 'Top Gun AA',
	torpedo: 'Torpedo',
	trackoffset: 'Track Offset',
	tracks: 'Tracks',
	trackstrength: 'Track Strength',
	trackstretch: 'Track Stretch',
	tracktype: 'Track Type',
	trackwidth: 'Track Width',
	trajectoryheight: 'Trajectory Height',
	transportByEnemy: 'Transport By Enemy',
	transportbyenemy: 'Transport By Enemy',
	transportcapacity: 'Transport Capacity',
	transportmass: 'Transport Mass',
	transportsize: 'Transport Size',
	transportunloadmethod: 'Transport Unload Method',
	treeshader: 'Tree Shader',
	tremor_spread_fire: 'Tremor Spread Fire',
	trident_depthcharge: 'Trident Depth Charge',
	trigger: 'Trigger',
	turninplace: 'Turn In Place',
	turninplaceanglelimit: 'Turn In Place Angle Limit',
	turninplacespeedlimit: 'Turn In Place Speed Limit',
	turnradius: 'Turn Radius',
	turnrate: 'Turn Rate',
	turret: 'Turret',
	turretname: 'Turret Name',
	ultraheavyriotcannon: 'Ultra Heavy Riot Cannon',
	uncloak: 'Uncloak',
	underattack: 'Under Attack',
	unitcomplete: 'Unit Complete',
	unitgroup: 'Unit Group',
	unitname: 'Unit ID', // Internal ID/Script Name
	unloadspread: 'Unload Spread',
	upright: 'Upright',
	usePieceCollisionVolumes: 'Use Piece Collision Volumes',
	usebuildinggrounddecal: 'Use Building Ground Decal',
	usepiececollisionvolumes: 'Use Piece Collision Volumes',
	useskinning: 'Use Skinning',
	usesmoothmesh: 'Use Smooth Mesh',
	velgun: 'Vel Gun', // Velocity Gun?
	verticalspeed: 'Vertical Speed',
	vipersabot: 'Viper Sabot',
	vtol_emg: 'VTOL EMG',
	vtol_emg2: 'VTOL EMG 2',
	vtol_rocket: 'VTOL Rocket',
	vtol_rocket2: 'VTOL Rocket 2',
	vtol_sabot: 'VTOL Sabot',
	water_fall_damage_multiplier: 'Water Fall Damage Multiplier',
	waterballon: 'Water Balloon',
	waterbounce: 'Water Bounce',
	waterline: 'Water Line',
	waterweapon: 'Water Weapon',
	weapon: 'Weapon', // Could be default weapon or main weapon type
	weapon1turretx: 'Weapon 1 Turret X',
	weapon1turrety: 'Weapon 1 Turret Y',
	weaponAimAdjustPriority: 'Weapon Aim Adjust Priority',
	weapon_type: 'Weapon Type',
	weaponacceleration: 'Weapon Acceleration',
	weapondefs: 'Weapon Definitions',
	weapons: 'Weapons', // List or map of weapon slots/types
	weapontimer: 'Weapon Timer',
	weapontype: 'Weapon Type',
	weaponvelocity: 'Projectile Speed', // Common override for clarity
	windgenerator: 'Wind Generator',
	wingangle: 'Wing Angle',
	wingdrag: 'Wing Drag',
	wobble: 'Wobble',
	workertime: 'Build Speed', // Common override
	workertimeboost: 'Worker Time Boost', // Build Speed Boost
	working: 'Working',
	wpn1turretx: 'Wpn 1 Turret X',
	wpn1turrety: 'Wpn 1 Turret Y',
	wtboostunittype: 'WT Boost Unit Type', // Worker Time?
	yardmap: 'Yard Map', // Placement footprint/blockages
	yellow_missile: 'Yellow Missile'
};
