repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8 # Use the appropriate version
    hooks:
      - id: prettier
        types: [file]
        args: [--write]
        additional_dependencies:
          - prettier
          - prettier-plugin-svelte
          - svelte
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
