name: CI Build Test

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Restore units data cache
        uses: actions/cache@v3
        id: units-cache
        with:
          path: units-parser/cache
          key: ${{ runner.os }}-units-data-${{ hashFiles('units-parser/main.py', 'units-parser/GitHubDownloader.py') }}
          restore-keys: |
            ${{ runner.os }}-units-data-

      - name: Install Python dependencies
        run: |
          cd units-parser
          pip install -r requirements.txt

      - name: Run data parser
        run: |
          cd units-parser
          python main.py

      - name: Install Node dependencies
        run: pnpm install

      - name: Build site
        run: |
          BASE_PATH="/${{ github.event.repository.name }}" pnpm run build

      - name: Check build output
        run: |
          if [ -d "build" ]; then
            echo "✅ Build completed successfully"
            ls -la build
          else
            echo "❌ Build directory not found"
            exit 1
          fi
